### ISSUE TITLE
Wrong generated pivot Class Name

### ISSUE THREAD

**Issue by arturmamedov** [laracasts/Laravel-5-Generators-Extended#109]
#### Laravel-5-Generators-Extended version `1.1.3`

run comand: `php artisan make:migration:pivot pricelist_services pricelist_types`

Generated class name: `CreatePricelist_periodPricelist_typePivotTable` 
instead of `CreatePricelistPeriodPricelistTypePivotTable`

**Comment by akramabdulrahman** [comment]
Laravel-5-Generators-Extended version 1.1 

run php artisan make:migration:pivot sectors service_providers
generated CreateSectorService_providerPivotTable 
instead of CreateSectorServiceProviderPivotTable

**Comment by cs-abdulwahab** [comment]
same issue  that took my entire day

**Comment by S4Mi** [comment]
<code>php artisan make:migration:pivot courses levels</code> generated <code>class App\ extends Migration</code> ! no class name.

**Comment by cs-abdulwahab** [comment]
now pivot is causing issue in laravel 5.4
after renaming the class 
on migrate    class not found exception occur

have applied   composer dump-autoload   etc

**Comment by mklahorst** [comment]
Have same issue as @S4Mi , but it also changes the table name "media" to "medium" when running:

`php artisan make:migration:pivot media submissions`

And generates `medium_submission` for the table and `medium_id` for the column name.

**Comment by bogdankharchenko** [comment]
both issues are addressed in this PR, https://github.com/laracasts/Laravel-5-Generators-Extended/pull/154

**Comment by Behinder** [comment]
One year later, error still persist

**Comment by mzummo** [comment]
same here! if i get the time i'll try to take a look at the issue and submit a PR (can someone confirm the issue still exists and is not a fluke/user error?)

**Comment by tabacitu** [comment]
Hi guys, I'm sorry for taking years to get to this. I'm afraid I can't put too much time into this particular repo.

The PR had been merged for a while, so it was available if you installed it using ```composer require laracasts/generators:master --dev```. But now I've also tagged 1.1.5 - so the fix is widely available.

Sorry for not getting involved into this sooner. You know... life got in the way. If anybody has the time and chops to become a maintainer, please let me know - I'd love it if this repo got the attention it deserves.

Cheers!
